/* Character list ----------------------------------- */

    game_data['chr_all'] = {
         '1' : [ "Amy",                        null,                 1, 0, 0 ],
         '2' : [ "Amy",                        "Nightlife",          4, 0, 0 ],
         '3' : [ "Amy",                        "Amazonian",          0, 0, 1 ],
         '4' : [ "Ben Franklin",               null,                 1, 0, 3 ],
         '5' : [ "Bender",                     null,                 2, 0, 0 ],
         '6' : [ "Bender",                     "Bee",                4, 0, 3 ],
         '7' : [ "Bender",                     "Burglar",            2, 0, 0 ],
         '8' : [ "Bender",                     "Ghost",              4, 0, 0 ],
         '9' : [ "Bender",                     "Golden",             4, 0, 0 ],
        '10' : [ "Bender",                     "Hunter",             3, 0, 2 ],
        '11' : [ "Bender",                     "Pharaoh",            0, 0, 3 ],
        '12' : [ "Bender",                     "Ramblin' Rodriguez", 3, 0, 0 ],
        '13' : [ "Bender's Mom",               null,                 2, 0, 1 ],
        '14' : [ "Bev",                        null,                 3, 0, 0 ],
        '15' : [ "Bill Nye",                   null,                 1, 0, 1 ],
        '16' : [ "Billionairebot",             null,                 2, 0, 0 ],
        '17' : [ "Blatherbot",                 null,                 2, 0, 3 ],
        '18' : [ "The Borax Kid",              null,                 0, 0, 1 ],
        '19' : [ "Boxy",                       null,                 3, 0, 1 ],
        '20' : [ "Butcher Bot",                null,                 2, 0, 1 ],
        '21' : [ "Calculon",                   null,                 0, 0, 0 ],
        '22' : [ "Calculon",                   "Ghost",              2, 0, 3 ],
        '23' : [ "Calculon",                   "Shakespeare",        4, 0, 3 ],
        '24' : [ "Father Changstein El-Gamal", null,                 4, 0, 3 ],
        '25' : [ "Chris Hardwick",             null,                 0, 0, 3 ],
        '26' : [ "Crushinator",                null,                 4, 0, 3 ],
        '27' : [ "Destructor",                 null,                 0, 0, 3 ],
        '28' : [ "Dr. Cahill",                 null,                 1, 0, 1 ],
        '29' : [ "Mutant Dwayne",              null,                 4, 0, 1 ],
        '30' : [ "Fender",                     null,                 2, 0, 0 ],
        '31' : [ "Flexo",                      null,                 2, 0, 1 ],
        '32' : [ "Free Waterfall Jr.",         null,                 3, 0, 0 ],
        '33' : [ "Fry",                        null,                 3, 1, 0 ],
        '34' : [ "Fry",                        "Bachelor",           4, 0, 0 ],
        '35' : [ "Fry",                        "Devilish",           0, 0, 0 ],
        '36' : [ "Fry",                        "Robot",              2, 0, 0 ],
        '37' : [ "Fry",                        "Slurm Duke",         4, 0, 0 ],
        '38' : [ "George Takei",               null,                 0, 0, 3 ],
        '39' : [ "Hattie McDoogal",            null,                 0, 0, 0 ],
        '40' : [ "Hedonismbot",                null,                 2, 0, 0 ],
        '41' : [ "Hermes",                     null,                 4, 0, 0 ],
        '42' : [ "Hermes",                     "Mecha",              2, 0, 1 ],
        '43' : [ "Horrible Gelatinous Blob",   null,                 3, 0, 1 ],
        '44' : [ "Hookerbot",                  null,                 2, 0, 0 ],
        '45' : [ "The Professor",              null,                 1, 1, 0 ],
        '46' : [ "The Professor",              "Colonial",           0, 0, 3 ],
        '47' : [ "Hyper-Chicken",              null,                 4, 0, 1 ],
        '48' : [ "Kif",                        null,                 3, 0, 2 ],
        '49' : [ "Kif",                        "Cowboy",             3, 0, 2 ],
        '50' : [ "LaBarbara",                  null,                 4, 0, 1 ],
        '51' : [ "Leela",                      null,                 0, 0, 2 ],
        '52' : [ "Leela",                      "Colonial",           3, 0, 3 ],
        '53' : [ "Leela",                      "Lee Lemon",          3, 0, 3 ],
        '54' : [ "Leela",                      "Robot",              2, 0, 2 ],
        '55' : [ "Leg Mutant",                 null,                 3, 0, 0 ],
        '56' : [ "Lrrr",                       null,                 0, 0, 2 ],
        '57' : [ "Malfunctioning Eddie",       null,                 3, 0, 0 ],
        '58' : [ "Monique",                    null,                 4, 0, 2 ],
        '59' : [ "Neil deGrasse Tyson",        null,                 1, 0, 3 ],
        '60' : [ "Nixon & Agnew",              null,                 0, 0, 3 ],
        '61' : [ "Ndnd",                       null,                 4, 0, 2 ],
        '62' : [ "Pazuzu",                     null,                 3, 0, 1 ],
        '63' : [ "Mr. Peppy",                  null,                 3, 0, 3 ],
        '64' : [ "Lionel Preacherbot",         null,                 2, 0, 0 ],
        '65' : [ "Roberto",                    null,                 5, 0, 1 ],
        '66' : [ "Robot Devil",                null,                 5, 0, 2 ],
        '67' : [ "Robot Gypsy",                null,                 4, 0, 2 ],
        '68' : [ "Scruffy",                    null,                 4, 0, 1 ],
        '69' : [ "Slurms McKenzie",            null,                 0, 0, 0 ],
        '70' : [ "Smitty",                     null,                 3, 0, 1 ],
        '71' : [ "Stephen Hawking",            null,                 1, 0, 2 ],
        '72' : [ "URL",                        null,                 2, 0, 1 ],
        '73' : [ "URL",                        "Off-duty",           3, 0, 1 ],
        '74' : [ "Mutant Vyolet",              null,                 3, 0, 0 ]
    };